# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: all
  become: yes

  tasks:
    - name: Call Roles
      find:
        paths: /tmp
      register: cmd_result
    - debug:
        var: cmd_result

- hosts: all
  roles:
    - motd
     #  hosts: servers
     # roles:
   #- hostname
   #- firewalld
   #- ntp-config
   # - motd

